//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineLibraryMgtSystemDbEntities : DbContext
    {
        public OnlineLibraryMgtSystemDbEntities()
            : base("name=OnlineLibraryMgtSystemDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookFineTable> BookFineTables { get; set; }
        public virtual DbSet<BookReturnTable> BookReturnTables { get; set; }
        public virtual DbSet<BookTable> BookTables { get; set; }
        public virtual DbSet<BookTypeTable> BookTypeTables { get; set; }
        public virtual DbSet<DepartmentTable> DepartmentTables { get; set; }
        public virtual DbSet<DesignationTable> DesignationTables { get; set; }
        public virtual DbSet<EmployeeTable> EmployeeTables { get; set; }
        public virtual DbSet<IssueBookTable> IssueBookTables { get; set; }
        public virtual DbSet<PurchaseDetailTable> PurchaseDetailTables { get; set; }
        public virtual DbSet<PurchaseTable> PurchaseTables { get; set; }
        public virtual DbSet<PurTemDetailsTable> PurTemDetailsTables { get; set; }
        public virtual DbSet<SupplierTable> SupplierTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<UserTypeTable> UserTypeTables { get; set; }
    }
}
