//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PurTemDetailsTable
    {
        public int PurTemID { get; set; }

        [Required(ErrorMessage="Select Book")]
        public int BookID { get; set; }

        [Required(ErrorMessage = "Enter Purchase Qty")]
        public int Qty { get; set; }

        [Required(ErrorMessage = "Enter Purchase Unit Price")]
        public double UnitPrice { get; set; }
    
        public virtual BookTable BookTable { get; set; }
    }
}
